site_name: Hedy Lamar - Docs

repo_name: "Hedy Lamar - Docs"
repo_url: "https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01-HEDY-LAMAR"

nav:
  - Início: index.md
  - Fase 1: fase.md
  - GQM: GQM.md

theme:
  name: material

  features:
    - navigation.tabs
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: green

    - scheme: default
      toggle:
        icon: material/toggle-switch
      primary: green

  logo: img/icon.jpg
  favicon: img/icon.jpg


markdown_extensions:
  - attr_list
  - md_in_html
  
